/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContasBancariaSchema extends BaseModel {
  static $columns = ['balance', 'createdAt', 'id', 'numeroAgencia', 'numeroConta', 'updatedAt', 'usuarioId'] as const
  $columns = ContasBancariaSchema.$columns
  @column()
  declare balance: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare numeroAgencia: string
  @column()
  declare numeroConta: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usuarioId: number
}

export class EnderecoSchema extends BaseModel {
  static $columns = ['cidade', 'createdAt', 'estado', 'id', 'numero', 'rua', 'updatedAt', 'usuarioId'] as const
  $columns = EnderecoSchema.$columns
  @column()
  declare cidade: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare estado: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare numero: string
  @column()
  declare rua: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usuarioId: number
}

export class InvestimentoSchema extends BaseModel {
  static $columns = ['contaId', 'createdAt', 'id', 'status', 'tipoInvestimentoId', 'updatedAt', 'valor'] as const
  $columns = InvestimentoSchema.$columns
  @column()
  declare contaId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column()
  declare tipoInvestimentoId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare valor: string
}

export class TiposInvestimentoSchema extends BaseModel {
  static $columns = ['createdAt', 'descricao', 'id', 'nome', 'taxaRendimento', 'updatedAt'] as const
  $columns = TiposInvestimentoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descricao: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column()
  declare taxaRendimento: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TransacoeSchema extends BaseModel {
  static $columns = ['contaId', 'createdAt', 'descricao', 'id', 'tipo', 'updatedAt', 'valor'] as const
  $columns = TransacoeSchema.$columns
  @column()
  declare contaId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descricao: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare valor: string
}

export class UsuarioSchema extends BaseModel {
  static $columns = ['cpf', 'createdAt', 'email', 'id', 'nomeCompleto', 'role', 'senha', 'updatedAt'] as const
  $columns = UsuarioSchema.$columns
  @column()
  declare cpf: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nomeCompleto: string
  @column()
  declare role: string
  @column()
  declare senha: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
